# Generated by Django 6.0.5 on 2026-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0005_add_fk_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silveringestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='silveringestiontask',
            name='phase',
            field=models.CharField(blank=True, choices=[('attaching', 'Attaching to PostgreSQL'), ('counting_source', 'Counting source bronze rows'), ('transforming', 'Transforming and cleaning data'), ('inserting', 'Inserting into silver table'), ('counting_silver', 'Verifying silver row count'), ('verifying_insertion', 'Verifying ingested row count'), ('completed', 'Ingestion completed successfully')], default='', max_length=30),
        ),
    ]
