# Generated by Django 6.0.5 on 2026-05-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0003_add_progress_and_entry_task_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BronzeIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('simulation_source', models.CharField(max_length=255)),
                ('snapshot_type', models.CharField(max_length=50)),
                ('source_file_hash', models.CharField(db_index=True, max_length=64)),
                ('source_row_count', models.IntegerField(blank=True, null=True)),
                ('ingested_row_count', models.IntegerField(blank=True, null=True)),
                ('rejected_row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('landing_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bronze_ingestions', to='landing.landingupload')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BronzeIngestionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('step', models.CharField(default='ingest', max_length=20)),
                ('attempt', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('phase', models.CharField(blank=True, choices=[('attaching', 'Attaching to PostgreSQL'), ('counting_source', 'Counting source parquet rows'), ('inserting', 'Inserting into bronze table'), ('counting_ingested', 'Verifying ingested row count'), ('completed', 'Ingestion completed successfully')], default='', max_length=30)),
                ('worker_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('error_type', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rows', to='bronze.bronzeingestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ingestion', 'step', 'attempt'), name='unique_bronze_ingestion_step_attempt')],
            },
        ),
    ]
