# Generated by Django 6.0.5 on 2026-05-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronze', '0002_bronze_data_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronzeingestion',
            name='parse_progress_current',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bronzeingestion',
            name='parse_progress_description',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='bronzeingestion',
            name='parse_progress_total',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
