# Generated by Django 6.0.5 on 2026-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronze', '0004_add_fk_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronzeingestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
