# Generated by Django 6.0.5 on 2026-05-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('squad_snapshot', 'Squad Snapshot'), ('scouting_snapshot', 'Scouting Snapshot'), ('squad_matchstats_snapshot', 'Squad Match Stats')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ingame_date', models.DateField()),
                ('data_label', models.CharField(db_index=True, help_text='User-defined label e.g. winter_scouting, under_23_scouting', max_length=255)),
                ('simulation_source', models.CharField(max_length=255)),
                ('source_file_hash', models.CharField(max_length=64, unique=True)),
                ('source_file_name', models.CharField(max_length=500)),
                ('parquet_path', models.CharField(blank=True, default='', max_length=1000)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('save_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.savemaster')),
            ],
            options={
                'ordering': ['-upload_timestamp'],
                'indexes': [models.Index(fields=['save_master', 'snapshot_type'], name='landing_lan_save_ma_066db0_idx')],
            },
        ),
    ]
