# Generated by Django 6.0.5 on 2026-05-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingupload',
            name='celery_task_id',
        ),
        migrations.RemoveField(
            model_name='landingupload',
            name='error_message',
        ),
        migrations.AlterField(
            model_name='landingupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LandingZoneTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('step', models.CharField(choices=[('parse', 'Parse'), ('store', 'Store')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt', models.PositiveIntegerField()),
                ('worker_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('error_type', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rows', to='landing.landingupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('upload', 'step', 'attempt'), name='unique_upload_step_attempt')],
            },
        ),
    ]
