# Generated by Django 6.0.5 on 2026-05-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_landingupload_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingupload',
            name='entry_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='landingupload',
            name='parse_progress_current',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landingupload',
            name='parse_progress_description',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='landingupload',
            name='parse_progress_total',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
