# Generated by Django 6.0.5 on 2026-06-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_landingupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingupload',
            name='season',
            field=models.CharField(default='2023-2024', max_length=20),
            preserve_default=False,
        ),
    ]
